### ISSUE TITLE
Procedure for installing AstrodynamicsPlots.jl, GMAT.jl

### ISSUE THREAD

**Issue by OrbitalMechanic** [JuliaAstrodynamics/AstrodynamicsPlots.jl#1]
I'm attempting to install AstrodynamicsPlots.jl and GMAT.jl in Julia 0.5.0 running on a MacPro running Mac OS X version 10.12.2 (Sierra). I'm relatively new to Julia and I'd like to know how to install the AstrodynamicsPlots.jl and GMAT.jl.

Sam Dupree.

**Comment by helgee** [comment]
Hi Sam,

thanks for wanting to try out those packages but they are still in a very experimental state. Especially `AstrodynamicsPlots.jl` is just a skeleton package at the moment and does not contain any code, yet. My plan is to split my [Astrodynamics.jl](https://github.com/JuliaAstrodynamics/Astrodynamics.jl) package which has grown quite large into several smaller packages. I have not gotten around to it though since I am starting a new job next month. What kind of functionality do you need?

GMAT.jl is also still in its infancy and does not do much. But I will soon update it for the latest GMAT version.

**Comment by OrbitalMechanic** [comment]
Helge,

I was interested in seeing how Astrodynamics.jl and 
AstrodynamicsPlots.jl compared with poliastro. As for GMAT.jl I wanted 
to see how it works with GMAT.

Hope this helps.

Sam Dupree.
